# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertype',
            name='department',
        ),
    ]
