# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160705_1934'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GrantID',
            new_name='Grant',
        ),
        migrations.AlterModelOptions(
            name='grant',
            options={},
        ),
    ]
