# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160705_1954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'permissions': (('view_document', 'View document'),)},
        ),
        migrations.AlterModelOptions(
            name='grant',
            options={'permissions': (('view_grant', 'View Grant'),)},
        ),
    ]
