# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20160707_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d')),
            ],
        ),
    ]
